#!/usr/bin/env bash

hello() {
    local s=$1
    echo "hello $s"
}

goodbye() {
    local s=$1
    echo "goodbye $s"
}

if (( $# == 0 )); then
    # >&2 == stderr, where error messages go
    echo 'name required!' >&2
    exit 1
fi

for name in "$@"; do
    # you can't quote the wildcarded expression!!
    case $name in 
        d* | b*) hello "$name";;
        *)  goodbye "$name";;
    esac
done
